source "https://rubygems.org"

gem "minimal-mistakes-jekyll", path: "../"

gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem "jekyll-archives"
end