remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "air"

# Site Settings
locale: "en-US"
title: "Aditya Soenarjo"
title_separator: "|"
name: "Aditya Soenarjo"
description: "Personal academic website of Aditya Soenarjo, Economist at the Federal Reserve Bank of Boston."
url: "https://soenarjo.github.io"
repository: "soenarjo/soenarjo.github.io"

# Site Author
author:
  name: "Aditya Soenarjo"
  avatar: "/assets/images/headshot.jpg"
  bio: "Economist, Federal Reserve Bank of Boston"
  location: "Boston, MA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:adityasoenarjo@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/adisoenarjo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/soenarjo"
    - label: "CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "https://nbviewer.org/github/soenarjo/website/blob/main/CV_Soenarjo.pdf"

# Social Sharing
twitter:
  username: "adisoenarjo"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/adisoenarjo"

# Reading Files
include:
  - _pages
exclude:
  - vendor
  - .bundle
  - Gemfile
  - LICENSE
  - README

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Outputting
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
