---
title: "Code of Conduct"
description: |
 The SIPBS CompBiol Group Code of Conduct
about:
  template: marquee
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/scompbiol
    - icon: github
      text: Github
      href: https://github.com/sipbs-compbiol
    - icon: envelope
      text: Email
      href: mailto:leighton.pritchard@strath.ac.uk
html:
  anchor-sections: true
---

::: {.callout-important}
## Summary

**This group aims to be a supportive, encouraging environment for producing excellent science.** We subscribe to and support the University of Strathclyde's unacceptable behaviour and personal relationship policies:

- University of Strathclyde Unacceptable Behaviour Policy [[pdf]](https://www.strath.ac.uk/media/1newwebsite/documents/complaintsprocedure/Unacceptable_Behaviour_Policy.pdf)
- University of Strathclyde Staff Personal Relationship Policy [[pdf]](https://www.strath.ac.uk/media/ps/humanresources/policies/Staff_Personal_Relationships_Policy.pdf)
:::

::: {.callout-warning}
## Other University Policies

Members of the group are also expected to follow all other applicable university policies, including the following:

- Alcohol, drugs, and substance misuse [[pdf]](https://www.strath.ac.uk/media/ps/humanresources/policies/Alcohol_Drugs_Substances_Misuse_Policy.pdf)
- Dignity and respect policy [[pdf]](https://www.strath.ac.uk/media/ps/humanresources/policies/DignityandRespectPolicy.pdf)
- Use of social media [[pdf]](https://www.strath.ac.uk/media/ps/humanresources/policies/Guidance_on_the_Use_of_Social_Media.pdf)
:::

::: {.callout-tip collapse="true"}
## Social Media

We encourage posting about our science and culture on social media, but please keep in mind that posting about work issues from a personal account can be in breach of university policies, as this extract notes:

> "Inappropriate use of social media, whether at work or in a private capacity, can potentially violate the privacy, breach the security and/or harm the reputations of colleagues, students and/or the University. Breaches of these guidelines such as bullying of colleagues or social media activity which causes reputational damage to the University may constitute misconduct and could result in disciplinary action being taken."
:::

Further details, and more policies, can be found on the [University of Strathclyde HR Policies and Procedures page](https://www.strath.ac.uk/staff/policies/hr/).

In addition, all members of the lab, along with visitors, are expected to agree with the following code of conduct. We will enforce this code as needed. We expect cooperation from all members to help in ensuring a safe and productive working environment for everybody.

## The Quick Version

The group is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof).

::: {.callout-important}
## We do not tolerate harassment of group members in any form.
:::

## The Less Quick Version

Harassment includes offensive comments related to sex, gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

::: {.callout-important}
Group members asked to stop any harassing behavior are expected to comply immediately.
:::

::: {.callout-tip}
## What to do if you have an issue

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact [Leighton Pritchard](mailto:leighton.pritchard@strath.ac.uk) immediately. For official concerns, or if Leighton is the cause of your concern, please follow the standard [University of Strathclyde complaints procedure](https://www.strath.ac.uk/contactus/complaintsprocedure/).
:::

We expect members to follow these guidelines at any work-related event.

::: {.callout-note collapse="true"}
## Credit

Original source and credit: [http://confcodeofconduct.com/](http://confcodeofconduct.com/). Please help by translating or improving: [http://github.com/confcodeofconduct/confcodeofconduct.com](http://github.com/confcodeofconduct/confcodeofconduct.com). This work is licensed under a Creative Commons Attribution 3.0 Unported License
:::