---
title: "Group Philosophy"
description: |
 The SIPBS CompBiol Group philosophy
about:
  template: marquee
  links:
    - text: "{{< fa brands bluesky >}} Bluesky"
      href: https://bsky.app/profile/sipbscompbiol.bsky.social
    - icon: github
      text: Github
      href: https://github.com/sipbs-compbiol
    - icon: envelope
      text: Email
      href: mailto:leighton.pritchard@strath.ac.uk
toc: true
html:
  anchor-sections: true
---

::: {.callout-tip}
## Summary

**Our primary focus is on enabling better biology through method development, data analysis and software.**

Biology is increasingly a data-intensive science in need of tools, techniques and expertise to extract accurate and useful insights. Our role spans from development of novel software and general computational/modelling approaches to biological problems, to full collaborations on specific biological projects.

We work mostly in the areas of 'omics (genomics/metagenomics, metabolomics, and transcriptomics) and modelling, with a focus on microbiology.
:::

## Open Science

To the best of the group's ability, we practice open science. 

::: {.callout-important}
## Our default is to be “open”.
:::

- we aim to make all software available under an [MIT open source license](https://opensource.org/licenses/MIT)
- we aim to write our papers openly and submit to preprint servers.
- we aim to make data available as soon as practical.
- we invite and welcome collaboration.

::: {.callout-note}
## Social Media

We do encourage blogging and open discussion of research on social media.
:::

::: {.callout-warning}
## Privacy, GDPR, Anonymity

This does not override issues arising from GDPR, or genuine privacy and anonymity concerns. In particular, when dealing with medical data and results deriving from human samples we make every endeavour to preserve anonymity.
:::

## Other Notes

::: {.callout-note}
## Code of Conduct

We have a code of conduct. Please see the [Group Code of Conduct](/code_of_conduct.qmd).
:::

### Programming languages

The first choice of language for writing software should be Python, in order to maximize reuse and remixability within the lab. This does not exclude use of other languages (Bash, R, Rust, MATLAB, C++, Julia, Go, etc.) where they are more appropriate to the task.

### Taking ideas with you

Postdocs are generally welcome to take projects with them and collaborate on group projects after they leave the group, although Leighton may have suggestions to help with career considerations.

::: {.callout-important}
Given finite resources, not all problems are worth solving. Choose problems worthy of your time and energy.
:::


### Teaching

Teaching and training are core values within the group. However, please be mindful of the need to balance teaching and training with research efforts.
