---
title: "Group Responsibilities"
description: |
 Responsibilities and expectations of group members
about:
  template: marquee
  links:
    - text: "{{< fa brands bluesky >}} Bluesky"
      href: https://bsky.app/profile/sipbscompbiol.bsky.social
    - icon: github
      text: Github
      href: https://github.com/sipbs-compbiol
    - icon: envelope
      text: Email
      href: mailto:leighton.pritchard@strath.ac.uk
toc: true
html:
  anchor-sections: true
---

## Leighton's responsibilities as PI:

- find funding, or give fair notice when funding is going to lapse;
- make himself available for meetings when necessary;
- handle administrative and paperwork issues;
- provide scientific leadership;
- provide career guidance and help group members work towards their career goals;
- resolve disputes within the group;
- write references and recommendation letters to support people in the lab as well as former lab members;

## PhD student responsibilities:

- meet their reporting, course and exam requirements;
- identify and develop research projects with the help of the PI;
- apply effort to their research and work towards a PhD-worthy body of work;
- attend and present at lab meetings, journal clubs, and Hacky Hours;
- (optional) submit weekly report;

## Postdoc responsibilities:

- identify and develop research projects with the help of the PI;
- attend and present at lab meetings, journal clubs, and Hacky Hours;
- define their career goals and work towards them;
- pursue projects and collaborations that further their own career goals;
- provide scientific and technical leadership within the lab;
- (optional) submit weekly report;

## Visiting student (UG/Msc) responsibilities: {#sec-student-responsibilities}

- meet their reporting, course and exam requirements;
- apply effort to their research and work towards their final report;
- attend and present at lab meetings and journal clubs;
- submit weekly report;

## Technical staff responsibilities:

- focus about 80% of their effort on priorities defined by the PI;
- attend lab meetings;
- submit weekly report;
- define their career goals and work towards them;

## Weekly reports: {#sec-weekly-reports}

Weekly reports are a way to report what group members have been up to; this provides both Leighton and the group member with context and trajectory going forward, and means that in-person meetings can focus on specific issues rather than be more general reporting. Weekly reports can be emailed to Leighton privately or to the whole lab.

Weekly reports can and should be minimalist - basically, list

- what you’ve been working on for the lab, including progress made and obstacles overcome;
- deferred items and upcoming issues;
- long term goals;
- work-related travel;
- anything else you want Leighton to know, including personal issues;

::: {.callout-tip}
## Weekly report advice

If most of the weekly report can be copy-pasted from the previous week, feel free to do so. If it takes you more than 60 minutes to do each week, you’re probably overthinking it.
:::
