FROM nvcr.io/nvidia/l4t-base:r32.5.0
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
  apt-get install python3-pip -y && \
  pip3 install -U pip && \
  apt-get install libhdf5-serial-dev hdf5-tools libhdf5-dev zlib1g-dev \
    zip libjpeg8-dev liblapack-dev libblas-dev gfortran -y && \
  apt-get install python3 python-dev python3-dev build-essential \
    libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev -yq && \
  pip install -U Cython \
    testresources setuptools==49.6.0 \
    numpy==1.16.1 h5py==2.10.0 \
    future==0.18.2 mock==3.0.5 keras_preprocessing==1.1.1 keras_applications==1.0.8 gast==0.2.2 futures protobuf pybind11 \
    grpcio absl-py py-cpuinfo psutil portpicker gast astor termcolor wrapt google-pasta && \
  pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v45 tensorflow