name: Update Algolia

on:
  push:
    branches:
      - main
            
jobs:
  update-algolia:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Actually Update Algolia
      env: 
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      run: |
        cd docs
        bundle install --gemfile=./Gemfile --jobs 4 --retry 3
        bundle exec jekyll build --config ./_config.yml --source . --destination ./_site 
        bundle exec jekyll algolia --config ./_config.yml --source . --destination ./_site 
